version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DATABASE=app
    links:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app
    volumes:
      - ./:/etc/postgresql
      - postgres_storage:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - '15431:5432'

volumes:
  postgres_storage:
